### ISSUE TITLE
safezones too smul

### ISSUE THREAD

**Issue by MistuhKleen** [APolarBaer/SpodularArma#3]

**Comment by MistuhKleen** [comment]
Still not updated

**Comment by MistuhKleen** [comment]
Safezones don't seem to exist at all

**Comment by APolarBaer** [comment]
Boriana Trader Safezone is working

**Comment by APolarBaer** [comment]
Selca Trader Safzone is working

**Comment by APolarBaer** [comment]
Arnoldstein Trader Safezone is working
