### ISSUE TITLE
Traders killable

### ISSUE THREAD

**Issue by MistuhKleen** [APolarBaer/SpodularArma#4]

**Comment by APolarBaer** [comment]
Selca Vehicle trader fixed, others not
Arnoldstein not fixed
Boriana not fixed

**Comment by MistuhKleen** [comment]
Assuming other traders are also unfixed at this point.

**Comment by MistuhKleen** [comment]
Boriana fixed

**Comment by APolarBaer** [comment]
Should all be fixed
